name: Bittu Reminder Scheduler
on:
  schedule:
    - cron: '* * * * *'  # Every minute
  workflow_dispatch:  # Allows manual testing

jobs:
  check-reminders:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger n8n reminder check
        run: |
          curl -X POST \
            "${{ secrets.N8N_WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            -d '{
              "source": "github_actions",
              "timestamp": "'$(date -u +%s)'",
              "action": "check_pending_reminders"
            }'
